name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qt5-qmake

      - name: Build project
        run: |
          qmake TIC_TAC_TOE_CPP_QT_SQLITE.pro
          make

      - name: Run tests
        run: |
          ./tst_testcase.cpp
