name: CI

on:
  push:
  pull_request:

jobs:
  continous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qt5-qmake xvfb

      - name: Build unit tests
        run: |
          cd UNITTESTx
          qmake UNITTESTx.pro
          mingw32-make

      - name: Build and test 'MyQtTest'
        run: |
          cd QtTest
          qmake QtTest.pro
          make
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./MyQtTest

      - name: Build and test 'Mydatabase_test'
        run: |
          cd database_test
          qmake database_test.pro
          make
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./Mydatabase_test

      - name: Build and test 'Mygametest'
        run: |
          cd gametest
          qmake gametest.pro
          make
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./Mygametest

      - name: Build and test 'Myaitest'
        run: |
          cd aitest
          qmake aitest.pro
          make
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./Myaitest

      - name: Build and test 'MyQtTest2'
        run: |
          cd QtTest2
          qmake QtTest2.pro
          make
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./MyQtTest2

  continous-deployment:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          choco install qt5-default

      - name: Build and test 'TIC_TAC_TOE_CPP_QT_SQLITE'
        run: |
          cd build/Executable/release
          ./TIC_TAC_TOE_CPP_QT_SQLITE.exe
