name: CI

on:
  push:
  pull_request:

jobs:
  test-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qt5-qmake xvfb

      - name: Debug UI file contents
        run: |
          cat mainwindow.ui  # Print contents of mainwindow.ui for debugging

      - name: Generate ui_mainwindow.h
        run: |
          if ! uic mainwindow.ui -o ui_mainwindow.h; then
            echo "Error: Failed to generate ui_mainwindow.h"
            exit 1  # Exit with error if uic fails
          fi

      - name: Build project
        run: |
          mkdir build2
          cd build2
          qmake ../GUI/semi.pro
          make

      - name: Run executable
        shell: bash
        run: |
          cd build2
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./ttt
