name: CI

on:
  push:
  pull_request:

jobs:
  test-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qt5-qmake

      - name: Build and test 'MyQtTest'
        run: |
          cd QtTest
          qmake QtTest.pro
          make
          ./MyQtTest

      - name: Build and test 'Mydatabase_test'
        run: |
          cd ..
          qmake database_test/database_test.pro
          make
          ./database_test/Mydatabase_test
