name: CI

on:
  push:
  pull_request:

jobs:
  test-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Qt dependencies
        uses: actions/cache@v2
        with:
          path: |
            /usr/lib/x86_64-linux-gnu/qt5
            /usr/include/x86_64-linux-gnu/qt5
          key: ${{ runner.os }}-qt-${{ hashFiles('**/QtTest/QtTest.pro') }}  # Change the key based on your project setup

      - name: Install Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qt5-qmake

      - name: Build project
        run: |
          qmake QtTest/QtTest.pro
          make

      - name: Run tests
        run: |
          ./MyQtTest
