name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qt5-qmake

      - name: Run moc
        run: |
          moc test_player.cpp -o test_player.moc

      - name: Build project
        run: |
          qmake tictactoeTest2/tictactoeTest.pro
          make

      - name: Run tests
        run: |
          ./tictacetoeTest
